vim.opt.background = "dark"
vim.opt.clipboard = "unnamedplus"
vim.opt.colorcolumn = "80"
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.mouse = ""
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 16
vim.opt.shiftwidth = 0
vim.opt.signcolumn = "yes"
vim.opt.smartindent = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.timeoutlen = 500
vim.opt.undodir = "/home/david/.vim/undodir"
vim.opt.undofile = true
vim.log_level = "debug"
vim.presence_log_level = "debug"
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
